### ISSUE TITLE
Can Javenode support Android? I am using it on Android and received an error message

### ISSUE THREAD

**Issue by miniphper** [caoccao/Javenode#7]
build.gradle:
    implementation 'com.caoccao.javet:javet-android:3.0.4'
    implementation "com.caoccao.javet:javenode:0.4.0"

A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.caoccao.javet.annotations.CheckReturnValue found in modules javet-3.0.3 (com.caoccao.javet:javet:3.0.3) and javet-android-3.0.4-runtime (com.caoccao.javet:javet-android:3.0.4)

**Comment by caoccao** [comment]
Yes, it supports Android. Please check [this file](https://github.com/caoccao/JavetShell/blob/main/android/app/build.gradle.kts) out. You need to explicitly exclude a package.

**Comment by miniphper** [comment]
> Yes, it supports Android. Please check [this file](https://github.com/caoccao/JavetShell/blob/main/android/app/build.gradle.kts) out. You need to explicitly exclude a package.

2024-02-22 18:17:17.861 12385-12385 System.out              top.deeke.script                     I  10:17:17.861 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
2024-02-22 18:17:17.865 12385-12385 System.out              top.deeke.script                     I  10:17:17.865 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
2024-02-22 18:17:17.866 12385-12385 System.out              top.deeke.script                     I  10:17:17.865 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Platform: Android
2024-02-22 18:17:17.866 12385-12385 System.out              top.deeke.script                     I  10:17:17.866 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 6
2024-02-22 18:17:17.867 12385-12385 System.out              top.deeke.script                     I  10:17:17.867 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Platform: Android
2024-02-22 18:17:17.868 12385-12385 System.out              top.deeke.script                     I  10:17:17.868 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
2024-02-22 18:17:17.869 12385-12385 System.out              top.deeke.script                     I  10:17:17.868 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: unavailable: sun.misc.Unsafe.copyMemory [class java.lang.Object, long, class java.lang.Object, long, long]
2024-02-22 18:17:17.869 12385-12385 System.out              top.deeke.script                     I  10:17:17.869 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, {int,long}): unavailable
2024-02-22 18:17:17.870 12385-12385 System.out              top.deeke.script                     I  10:17:17.869 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: unavailable (Android)
2024-02-22 18:17:17.870 12385-12385 op.deeke.scrip          top.deeke.script                     W  Accessing hidden method Lsun/misc/VM;->maxDirectMemory()J (unsupported, reflection, allowed)
2024-02-22 18:17:17.870 12385-12385 System.out              top.deeke.script                     I  10:17:17.870 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /data/user/0/top.deeke.script/cache (java.io.tmpdir)
2024-02-22 18:17:17.871 12385-12385 System.out              top.deeke.script                     I  10:17:17.871 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (os.arch: x86_64)
2024-02-22 18:17:17.873 12385-12385 System.out              top.deeke.script                     I  10:17:17.872 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
2024-02-22 18:17:17.873 12385-12385 System.out              top.deeke.script                     I  10:17:17.873 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
2024-02-22 18:17:17.874 12385-12385 System.out              top.deeke.script                     I  10:17:17.874 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: true
2024-02-22 18:17:17.875 12385-12385 System.out              top.deeke.script                     I  10:17:17.874 [main] INFO io.netty.util.internal.PlatformDependent - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
2024-02-22 18:17:17.886 12385-12385 System.out              top.deeke.script                     I  10:17:17.885 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
2024-02-22 18:17:17.886 12385-12385 System.out              top.deeke.script                     I  10:17:17.886 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
2024-02-22 18:17:17.902 12385-12385 System.out              top.deeke.script                     I  10:17:17.901 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
2024-02-22 18:17:17.909 12385-12385 System.out              top.deeke.script                     I  10:17:17.908 [main] DEBUG io.netty.util.concurrent.GlobalEventExecutor - -Dio.netty.globalEventExecutor.quietPeriodSeconds: 1
2024-02-22 18:17:17.916 12385-12385 System.out              top.deeke.script                     I  10:17:17.915 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
2024-02-22 18:17:17.916 12385-12385 System.out              top.deeke.script                     I  10:17:17.916 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
2024-02-22 18:17:17.921 12385-12385 System.out              top.deeke.script                     I  10:17:17.921 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
2024-02-22 18:17:17.921 12385-12385 System.out              top.deeke.script                     I  10:17:17.921 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
2024-02-22 18:17:17.924 12385-12385 System.out              top.deeke.script                     I  10:17:17.923 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: unavailable
2024-02-22 18:17:17.927 12385-12385 op.deeke.scrip          top.deeke.script                     W  Accessing hidden field Lsun/nio/ch/SelectorImpl;->selectedKeys:Ljava/util/Set; (unsupported, reflection, allowed)
2024-02-22 18:17:17.927 12385-12385 op.deeke.scrip          top.deeke.script                     W  Accessing hidden field Lsun/nio/ch/SelectorImpl;->publicSelectedKeys:Ljava/util/Set; (unsupported, reflection, allowed)
2024-02-22 18:17:17.932 12385-12385 System.out              top.deeke.script                     I  10:17:17.932 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
2024-02-22 18:17:17.932 12385-12385 System.out              top.deeke.script                     I  10:17:17.932 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
2024-02-22 18:17:17.935 12385-12385 System.out              top.deeke.script                     I  10:17:17.935 [main] DEBUG io.netty.util.NetUtilInitializations - Loopback interface: lo (lo, ::1)
2024-02-22 18:17:17.933 12385-12385 op.deeke.script         top.deeke.script                     W  type=1400 audit(0.0:1204): avc: denied { read } for name="somaxconn" dev="proc" ino=113169 scontext=u:r:untrusted_app:s0:c47,c257,c512,c768 tcontext=u:object_r:proc_net:s0 tclass=file permissive=0 app=top.deeke.script
2024-02-22 18:17:17.939 12385-12385 System.out              top.deeke.script                     I  10:17:17.937 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
2024-02-22 18:17:17.940 12385-12385 System.out              top.deeke.script                     I  java.io.FileNotFoundException: /proc/sys/net/core/somaxconn: open failed: EACCES (Permission denied)
2024-02-22 18:17:17.940 12385-12385 System.out              top.deeke.script                     I  	at libcore.io.IoBridge.open(IoBridge.java:575)
2024-02-22 18:17:17.940 12385-12385 System.out              top.deeke.script                     I  	at java.io.FileInputStream.<init>(FileInputStream.java:160)
2024-02-22 18:17:17.940 12385-12385 System.out              top.deeke.script                     I  	at java.io.FileReader.<init>(FileReader.java:72)
2024-02-22 18:17:17.940 12385-12385 System.out              top.deeke.script                     I  	at io.netty.util.NetUtil$SoMaxConnAction.run(NetUtil.java:185)
2024-02-22 18:17:17.940 12385-12385 System.out              top.deeke.script                     I  	at io.netty.util.NetUtil$SoMaxConnAction.run(NetUtil.java:170)
2024-02-22 18:17:17.941 12385-12385 System.out              top.deeke.script                     I  	at java.security.AccessController.doPrivileged(AccessController.java:43)
2024-02-22 18:17:17.941 12385-12385 System.out              top.deeke.script                     I  	at io.netty.util.NetUtil.<clinit>(NetUtil.java:167)
2024-02-22 18:17:17.941 12385-12385 System.out              top.deeke.script                     I  	at io.netty.util.NetUtil.isIpV6AddressesPreferred(NetUtil.java:280)
2024-02-22 18:17:17.941 12385-12385 System.out              top.deeke.script                     I  	at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.<clinit>(DefaultDnsServerAddressStreamProvider.java:110)
2024-02-22 18:17:17.941 12385-12385 System.out              top.deeke.script                     I  	at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.defaultAddresses(DefaultDnsServerAddressStreamProvider.java:163)
2024-02-22 18:17:17.941 12385-12385 System.out              top.deeke.script                     I  	at io.vertx.core.impl.resolver.DnsResolverProvider.<init>(DnsResolverProvider.java:79)
2024-02-22 18:17:17.942 12385-12385 System.out              top.deeke.script                     I  	at io.vertx.core.impl.resolver.DnsResolverProvider.create(DnsResolverProvider.java:43)
2024-02-22 18:17:17.942 12385-12385 System.out              top.deeke.script                     I  	at io.vertx.core.spi.resolver.ResolverProvider.factory(ResolverProvider.java:40)
2024-02-22 18:17:17.942 12385-12385 System.out              top.deeke.script                     I  	at io.vertx.core.impl.AddressResolver.<init>(AddressResolver.java:78)
2024-02-22 18:17:17.942 12385-12385 System.out              top.deeke.script                     I  	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:222)
2024-02-22 18:17:17.942 12385-12385 System.out              top.deeke.script                     I  	at io.vertx.core.impl.VertxBuilder.vertx(VertxBuilder.java:229)
2024-02-22 18:17:17.943 12385-12385 System.out              top.deeke.script                     I  	at io.vertx.core.Vertx.vertx(Vertx.java:84)
2024-02-22 18:17:17.943 12385-12385 System.out              top.deeke.script                     I  	at com.caoccao.javet.javenode.JNEventLoop.<init>(JNEventLoop.java:62)
2024-02-22 18:17:17.943 12385-12385 System.out              top.deeke.script                     I  	at com.caoccao.javet.javenode.JNEventLoop.<init>(JNEventLoop.java:58)
2024-02-22 18:17:17.943 12385-12385 System.out              top.deeke.script                     I  	at top.deeke.script.ScriptActivity.script(ScriptActivity.java:124)
2024-02-22 18:17:17.943 12385-12385 System.out              top.deeke.script                     I  	at top.deeke.script.ScriptActivity.onCreate(ScriptActivity.java:119)
2024-02-22 18:17:17.943 12385-12385 System.out              top.deeke.script                     I  	at android.app.Activity.performCreate(Activity.java:8057)
2024-02-22 18:17:17.943 12385-12385 System.out              top.deeke.script                     I  	at android.app.Activity.performCreate(Activity.java:8037)
2024-02-22 18:17:17.943 12385-12385 System.out              top.deeke.script                     I  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
2024-02-22 18:17:17.944 12385-12385 System.out              top.deeke.script                     I  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
2024-02-22 18:17:17.944 12385-12385 System.out              top.deeke.script                     I  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
2024-02-22 18:17:17.944 12385-12385 System.out              top.deeke.script                     I  	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
2024-02-22 18:17:17.944 12385-12385 System.out              top.deeke.script                     I  	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2024-02-22 18:17:17.944 12385-12385 System.out              top.deeke.script                     I  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2024-02-22 18:17:17.944 12385-12385 System.out              top.deeke.script                     I  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
2024-02-22 18:17:17.944 12385-12385 System.out              top.deeke.script                     I  	at android.os.Handler.dispatchMessage(Handler.java:106)
2024-02-22 18:17:17.944 12385-12385 System.out              top.deeke.script                     I  	at android.os.Looper.loopOnce(Looper.java:201)
2024-02-22 18:17:17.944 12385-12385 System.out              top.deeke.script                     I  	at android.os.Looper.loop(Looper.java:288)
2024-02-22 18:17:17.945 12385-12385 System.out              top.deeke.script                     I  	at android.app.ActivityThread.main(ActivityThread.java:7870)
2024-02-22 18:17:17.945 12385-12385 System.out              top.deeke.script                     I  	at java.lang.reflect.Method.invoke(Native Method)
2024-02-22 18:17:17.945 12385-12385 System.out              top.deeke.script                     I  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
2024-02-22 18:17:17.945 12385-12385 System.out              top.deeke.script                     I  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2024-02-22 18:17:17.946 12385-12385 System.out              top.deeke.script                     I  Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
2024-02-22 18:17:17.946 12385-12385 System.out              top.deeke.script                     I  	at libcore.io.Linux.open(Native Method)
2024-02-22 18:17:17.946 12385-12385 System.out              top.deeke.script                     I  	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
2024-02-22 18:17:17.946 12385-12385 System.out              top.deeke.script                     I  	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
2024-02-22 18:17:17.946 12385-12385 System.out              top.deeke.script                     I  	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
2024-02-22 18:17:17.946 12385-12385 System.out              top.deeke.script                     I  	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7756)
2024-02-22 18:17:17.946 12385-12385 System.out              top.deeke.script                     I  	at libcore.io.IoBridge.open(IoBridge.java:561)
2024-02-22 18:17:17.946 12385-12385 System.out              top.deeke.script                     I  	... 36 common frames omitted
2024-02-22 18:17:17.947 12385-12385 System.out              top.deeke.script                     I  10:17:17.947 [main] WARN io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider - Default DNS servers: [/2001:4860:4860::8888:53, /2001:4860:4860::8844:53] (Google Public DNS as a fallback)
2024-02-22 18:17:17.959 12385-12385 System.out              top.deeke.script                     I  10:17:17.958 [main] DEBUG io.netty.resolver.dns.DnsNameResolver - Default ResolvedAddressTypes: IPV4_PREFERRED
2024-02-22 18:17:17.959 12385-12385 System.out              top.deeke.script                     I  10:17:17.959 [main] DEBUG io.netty.resolver.dns.DnsNameResolver - Localhost address: localhost/127.0.0.1
2024-02-22 18:17:17.960 12385-12385 System.out              top.deeke.script                     I  10:17:17.960 [main] DEBUG io.netty.resolver.dns.DnsNameResolver - Windows hostname: null
2024-02-22 18:17:17.963 12385-12385 System.out              top.deeke.script                     I  10:17:17.962 [main] DEBUG io.netty.resolver.dns.DnsNameResolver - Default search domains: []
2024-02-22 18:17:17.964 12385-12385 System.out              top.deeke.script                     I  10:17:17.964 [main] DEBUG io.netty.resolver.dns.DnsNameResolver - Default UnixResolverOptions{ndots=1, timeout=5, attempts=16}
2024-02-22 18:17:17.970 12385-12385 System.out              top.deeke.script                     I  10:17:17.970 [main] DEBUG io.netty.resolver.DefaultHostsFileEntriesResolver - -Dio.netty.hostsFileRefreshInterval: 0
2024-02-22 18:17:17.974 12385-12385 System.out              top.deeke.script                     I  10:17:17.972 [main] DEBUG io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider - failed to parse /etc/resolv.conf and/or /etc/resolver
2024-02-22 18:17:17.974 12385-12385 System.out              top.deeke.script                     I  java.lang.IllegalArgumentException: /etc/resolv.conf didn't provide any name servers
2024-02-22 18:17:17.974 12385-12385 System.out              top.deeke.script                     I  	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:107)
2024-02-22 18:17:17.974 12385-12385 System.out              top.deeke.script                     I  	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:133)
2024-02-22 18:17:17.974 12385-12385 System.out              top.deeke.script                     I  	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parseSilently(UnixResolverDnsServerAddressStreamProvider.java:72)
2024-02-22 18:17:17.974 12385-12385 System.out              top.deeke.script                     I  	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.provider(DnsServerAddressStreamProviders.java:151)
2024-02-22 18:17:17.974 12385-12385 System.out              top.deeke.script                     I  	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.<init>(DnsServerAddressStreamProviders.java:130)
2024-02-22 18:17:17.974 12385-12385 System.out              top.deeke.script                     I  	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder.<clinit>(DnsServerAddressStreamProviders.java:128)
2024-02-22 18:17:17.975 12385-12385 System.out              top.deeke.script                     I  	at io.netty.resolver.dns.DnsServerAddressStreamProviders.unixDefault(DnsServerAddressStreamProviders.java:117)
2024-02-22 18:17:17.975 12385-12385 System.out              top.deeke.script                     I  	at io.netty.resolver.dns.DnsServerAddressStreamProviders.platformDefault(DnsServerAddressStreamProviders.java:113)
2024-02-22 18:17:17.975 12385-12385 System.out              top.deeke.script                     I  	at io.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:67)
2024-02-22 18:17:17.975 12385-12385 System.out              top.deeke.script                     I  	at io.vertx.core.impl.resolver.DnsResolverProvider.<init>(DnsResolverProvider.java:105)
2024-02-22 18:17:17.975 12385-12385 System.out              top.deeke.script                     I  	at io.vertx.core.impl.resolver.DnsResolverProvider.create(DnsResolverProvider.java:43)
2024-02-22 18:17:17.975 12385-12385 System.out              top.deeke.script                     I  	at io.vertx.core.spi.resolver.ResolverProvider.factory(ResolverProvider.java:40)
2024-02-22 18:17:17.975 12385-12385 System.out              top.deeke.script                     I  	at io.vertx.core.impl.AddressResolver.<init>(AddressResolver.java:78)
2024-02-22 18:17:17.975 12385-12385 System.out              top.deeke.script                     I  	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:222)
2024-02-22 18:17:17.975 12385-12385 System.out              top.deeke.script                     I  	at io.vertx.core.impl.VertxBuilder.vertx(VertxBuilder.java:229)
2024-02-22 18:17:17.976 12385-12385 System.out              top.deeke.script                     I  	at io.vertx.core.Vertx.vertx(Vertx.java:84)
2024-02-22 18:17:17.976 12385-12385 System.out              top.deeke.script                     I  	at com.caoccao.javet.javenode.JNEventLoop.<init>(JNEventLoop.java:62)
2024-02-22 18:17:17.976 12385-12385 System.out              top.deeke.script                     I  	at com.caoccao.javet.javenode.JNEventLoop.<init>(JNEventLoop.java:58)
2024-02-22 18:17:17.976 12385-12385 System.out              top.deeke.script                     I  	at top.deeke.script.ScriptActivity.script(ScriptActivity.java:124)
2024-02-22 18:17:17.976 12385-12385 System.out              top.deeke.script                     I  	at top.deeke.script.ScriptActivity.onCreate(ScriptActivity.java:119)
2024-02-22 18:17:17.976 12385-12385 System.out              top.deeke.script                     I  	at android.app.Activity.performCreate(Activity.java:8057)
2024-02-22 18:17:17.976 12385-12385 System.out              top.deeke.script                     I  	at android.app.Activity.performCreate(Activity.java:8037)
2024-02-22 18:17:17.976 12385-12385 System.out              top.deeke.script                     I  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
2024-02-22 18:17:17.977 12385-12385 System.out              top.deeke.script                     I  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
2024-02-22 18:17:17.977 12385-12385 System.out              top.deeke.script                     I  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
2024-02-22 18:17:17.977 12385-12385 System.out              top.deeke.script                     I  	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
2024-02-22 18:17:17.977 12385-12385 System.out              top.deeke.script                     I  	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2024-02-22 18:17:17.977 12385-12385 System.out              top.deeke.script                     I  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2024-02-22 18:17:17.977 12385-12385 System.out              top.deeke.script                     I  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
2024-02-22 18:17:17.978 12385-12385 System.out              top.deeke.script                     I  	at android.os.Handler.dispatchMessage(Handler.java:106)
2024-02-22 18:17:17.978 12385-12385 System.out              top.deeke.script                     I  	at android.os.Looper.loopOnce(Looper.java:201)
2024-02-22 18:17:17.978 12385-12385 System.out              top.deeke.script                     I  	at android.os.Looper.loop(Looper.java:288)
2024-02-22 18:17:17.978 12385-12385 System.out              top.deeke.script                     I  	at android.app.ActivityThread.main(ActivityThread.java:7870)
2024-02-22 18:17:17.978 12385-12385 System.out              top.deeke.script                     I  	at java.lang.reflect.Method.invoke(Native Method)
2024-02-22 18:17:17.979 12385-12385 System.out              top.deeke.script                     I  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
2024-02-22 18:17:17.979 12385-12385 System.out              top.deeke.script                     I  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2024-02-22 18:17:18.019 12385-12411 V8Runtime               top.deeke.script                     E  Failed to call a function.
2024-02-22 18:17:18.020 12385-12411 V8Runtime               top.deeke.script                     E  java.lang.NoSuchMethodError: No virtual method call(Lcom/caoccao/javet/values/reference/IV8ValueObject;[Lcom/caoccao/javet/values/V8Value;)Lcom/caoccao/javet/values/V8Value; in class Lcom/caoccao/javet/values/reference/V8ValueFunction; or its super classes (declaration of 'com.caoccao.javet.values.reference.V8ValueFunction' appears in /data/app/~~aGJTfV_0LDVVoepwzlhywA==/top.deeke.script-3lsHrVMqTBwrvV3f79xjSw==/base.apk!classes15.dex)
                                                                                                    	at com.caoccao.javet.javenode.modules.timers.BaseTimersFunction.lambda$run$1$com-caoccao-javet-javenode-modules-timers-BaseTimersFunction(BaseTimersFunction.java:109)
                                                                                                    	at com.caoccao.javet.javenode.modules.timers.BaseTimersFunction$$ExternalSyntheticLambda1.handle(Unknown Source:4)
                                                                                                    	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:1045)
                                                                                                    	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:1016)
                                                                                                    	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:335)
                                                                                                    	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:328)
                                                                                                    	at io.vertx.core.impl.ContextInternal.emit(ContextInternal.java:206)
                                                                                                    	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:1034)
                                                                                                    	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
                                                                                                    	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
                                                                                                    	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
                                                                                                    	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
                                                                                                    	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
                                                                                                    	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
                                                                                                    	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
                                                                                                    	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                                                                                                    	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)
2024-02-22 18:17:18.020 12385-12385 V8Runtime               top.deeke.script                     I  undefined

**Comment by miniphper** [comment]
But it reported an error, like there is no corresponding file permission

**Comment by caoccao** [comment]
I'm not sure what happened at your end. At least you may clone my project JavetShell and add the features you want on top of it to see which step goes wrong.

By the way, I guess you might want to join the Javet WeChat group discussion. Ping me at discord, if you are fine with that.

**Comment by miniphper** [comment]
It took me a long time to finally solve it. Just upgrade the following library and you'll be fine
![微信截图_20240223225024](https://github.com/caoccao/Javenode/assets/30486761/e8a7c7fe-d29d-45f0-98d7-4e9bc54b2631)

**Comment by caoccao** [comment]
Please ping me at discord, and I'll send you the qrcode.
